export const toys = [
  { id: 'TOYXCO001', name: 'Lego Moto Ducati', price: 200000, category: 'Xe cộ', image: 'Toy001.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYXCO002', name: 'Siêu xe Hybrid', price: 300000, category: 'Xe cộ', image: 'Toy002.jpg', rating: 4.5, brand: 'Hot Wheels' },
  { id: 'TOYXCO003', name: 'Xe đua McLaren', price: 450000, category: 'Xe cộ', image: 'Toy003.jpg', rating: 5, brand: 'McLaren' },
  { id: 'TOYXCO004', name: 'Xe đua McLaren P1', price: 1900000, category: 'Xe cộ', image: 'Toy004.jpg', rating: 5, brand: 'McLaren' },
  { id: 'TOYXCO005', name: 'Xe Porsche 911', price: 850000, category: 'Xe cộ', image: 'Toy005.jpg', rating: 5, brand: 'Porsche' },
  { id: 'TOYTAU001', name: 'Tàu Titanic', price: 350000, category: 'Tàu thuyền', image: 'Toy006.jpg', rating: 5, brand: 'Titanic' },
  { id: 'TOYTAU002', name: 'Tàu Endurance', price: 150000, category: 'Tàu thuyền', image: 'Toy007.jpg', rating: 4.5, brand: 'Endurance' },
  { id: 'TOYTRE001', name: 'Dungeons & Dragons', price: 500000, category: 'Đồ chơi trẻ em', image: 'Toy008.jpg', rating: 5, brand: 'Hasbro' },
  { id: 'TOYVTR001', name: 'Tàu vũ trụ', price: 500000, category: 'Vũ trụ', image: 'Toy009.jpg', rating: 5, brand: 'NASA' },
  { id: 'TOYVTR002', name: 'Lego tàu vũ trụ NASA', price: 600000, category: 'Vũ trụ', image: 'Toy010.jpg', rating: 5, brand: 'NASA' },
  { id: 'TOYTRE002', name: 'Ngôi nhà Lego', price: 200000, category: 'Đồ chơi trẻ em', image: 'Toy011.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYTRE003', name: 'Lego tháp Eiffel', price: 1000000, category: 'Đồ chơi trẻ em', image: 'Toy012.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYXCO006', name: 'Xe cắm trại bãi biển', price: 200000, category: 'Xe cộ', image: 'Toy013.jpg', rating: 5, brand: 'Hot Wheels' },
  { id: 'TOYTRE004', name: 'Lâu đài thời trung cổ', price: 100000, category: 'Đồ chơi trẻ em', image: 'Toy014.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYTRE005', name: 'Lego máy bay', price: 750000, category: 'Đồ chơi trẻ em', image: 'Toy015.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYTRE006', name: 'Lego Star Wars', price: 900000, category: 'Đồ chơi trẻ em', image: 'Toy016.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYXCO007', name: 'Xe đồ chơi', price: 950000, category: 'Xe cộ', image: 'Toy017.jpg', rating: 5, brand: 'Hot Wheels' },
  { id: 'TOYTRE007', name: 'Lego Pikachu', price: 550000, category: 'Đồ chơi trẻ em', image: 'Toy018.jpg', rating: 4.5, brand: 'Lego' },
  { id: 'TOYXCO008', name: 'Xe ngựa bập bênh', price: 500000, category: 'Xe cộ', image: 'Toy019.jpg', rating: 4.5, brand: 'Fisher Price' },
  { id: 'TOYTRE008', name: 'Đồ chơi nấu ăn', price: 1200000, category: 'Đồ chơi trẻ em', image: 'Toy020.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYTRE009', name: 'Gấu nhồi bông', price: 700000, category: 'Đồ chơi trẻ em', image: 'Toy021.jpg', rating: 5, brand: 'Steiff' },
  { id: 'TOYVTR003', name: 'Lego vũ trụ', price: 850000, category: 'Vũ trụ', image: 'Toy022.jpg', rating: 4.5, brand: 'Lego' },
  { id: 'TOYVTR004', name: 'Lego tàu không gian', price: 650000, category: 'Vũ trụ', image: 'Toy023.jpg', rating: 4.5, brand: 'Lego' },
  { id: 'TOYVTR005', name: 'Lego xe vũ trụ', price: 800000, category: 'Vũ trụ', image: 'Toy024.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYTRE010', name: 'Lego Fortnite', price: 950000, category: 'Đồ chơi trẻ em', image: 'Toy025.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYTRE011', name: 'Lego nhà', price: 550000, category: 'Đồ chơi trẻ em', image: 'Toy026.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYTRE012', name: 'Lego xe đồ chơi', price: 750000, category: 'Đồ chơi trẻ em', image: 'Toy027.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYXCO009', name: 'Xe địa hình', price: 600000, category: 'Xe cộ', image: 'Toy028.jpg', rating: 4.5, brand: 'Hot Wheels' },
  { id: 'TOYTAU003', name: 'Đồ chơi khủng long', price: 400000, category: 'Tàu thuyền', image: 'Toy029.jpg', rating: 5, brand: 'Jurassic' },
  { id: 'TOYVTR006', name: 'Lego tàu chiến', price: 700000, category: 'Vũ trụ', image: 'Toy030.jpg', rating: 4.5, brand: 'Lego' },
  { id: 'TOYXCO010', name: 'Lego Xe Đua', price: 600000, category: 'Xe cộ', image: 'Toy031.jpg', rating: 4.5, brand: 'Hot Wheels' },
  { id: 'TOYTRE013', name: 'Gấu Capi', price: 500000, category: 'Đồ chơi trẻ em', image: 'Toy032.jpg', rating: 5, brand: 'Steiff' },
  { id: 'TOYTRE014', name: 'Captain Marvel', price: 700000, category: 'Đồ chơi trẻ em', image: 'Toy033.jpg', rating: 4.5, brand: 'Steiff' },
  { id: 'TOYTRE015', name: 'Gấu bông Megumi', price: 800000, category: 'Đồ chơi trẻ em', image: 'Toy034.jpg', rating: 5, brand: 'Steiff' },
  { id: 'TOYVTR007', name: 'Lego tàu không gian', price: 900000, category: 'Vũ trụ', image: 'Toy035.jpg', rating: 5, brand: 'NASA' },
  { id: 'TOYVTR008', name: 'Lego tàu không gian', price: 1300000, category: 'Vũ trụ', image: 'Toy036.jpg', rating: 4.5, brand: 'NASA' },
  { id: 'TOYTRE016', name: 'Lego Khu vườn', price: 800000, category: 'Đồ chơi trẻ em', image: 'Toy037.jpg', rating: 4.5, brand: 'Lego' },
  { id: 'TOYTAU004', name: 'Lego tàu lặn', price: 400000, category: 'Tàu thuyền', image: 'Toy038.jpg', rating: 5, brand: 'Titanic' },
  { id: 'TOYTRE017', name: 'Lego siêu nhân', price: 500000, category: 'Đồ chơi trẻ em', image: 'Toy039.jpg', rating: 4.5, brand: 'Lego' },
  { id: 'TOYTRE018', name: 'Pixel Petz', price: 800000, category: 'Đồ chơi trẻ em', image: 'Toy040.jpg', rating: 5, brand: 'Steiff' },
  { id: 'TOYXCO011', name: 'Siêu xe Mustang', price: 700000, category: 'Xe cộ', image: 'Toy041.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYTRE019', name: 'Lego cảnh sát', price: 600000, category: 'Đồ chơi trẻ em', image: 'Toy042.jpg', rating: 4.5, brand: 'Lego' },
  { id: 'TOYTRE020', name: 'Lego khủng long', price: 500000, category: 'Đồ chơi trẻ em', image: 'Toy043.jpg', rating: 5, brand: 'Jurassic' },
  { id: 'TOYTRE021', name: 'Lego cảnh sát', price: 400000, category: 'Đồ chơi trẻ em', image: 'Toy044.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYTRE022', name: 'Lego Spiderman', price: 300000, category: 'Đồ chơi trẻ em', image: 'Toy045.jpg', rating: 4.5, brand: 'Lego' },
  { id: 'TOYTAU005', name: 'Lego tàu thuyền', price: 200000, category: 'Tàu thuyền', image: 'Toy046.jpg', rating: 5, brand: 'Titanic' },
  { id: 'TOYTAU006', name: 'Lego tàu bay', price: 1000000, category: 'Tàu thuyền', image: 'Toy047.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYTRE023', name: 'Lego travel suitcase', price: 200000, category: 'Đồ chơi trẻ em', image: 'Toy048.jpg', rating: 4.5, brand: 'Lego' },
  { id: 'TOYTRE024', name: 'Lego Mario', price: 300000, category: 'Đồ chơi trẻ em', image: 'Toy049.jpg', rating: 5, brand: 'Lego' },
  { id: 'TOYXCO012', name: 'Xe đua Oracle', price: 700000, category: 'Xe cộ', image: 'Toy050.jpg', rating: 5, brand: 'Lego' },
];

